
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pro
 */
public class DataEntryForm extends java.awt.Frame {

    private Connection con;
    private PreparedStatement ps;
    
    public DataEntryForm() {
        initComponents();
        setSize(400,400);
        try{
        con=Data.connect();
        String sql="INSERT INTO EMP VALUES(?,?,?,?)";
        ps=con.prepareStatement(sql);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        t14 = new java.awt.TextField();
        t11 = new java.awt.TextField();
        t12 = new java.awt.TextField();
        t13 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setText("Desg");
        add(label1);
        label1.setBounds(60, 170, 80, 30);

        label2.setText("ECode");
        add(label2);
        label2.setBounds(60, 50, 80, 30);

        label3.setText("Name");
        add(label3);
        label3.setBounds(60, 90, 80, 30);

        label4.setText("Salary");
        add(label4);
        label4.setBounds(60, 130, 80, 30);
        add(t14);
        t14.setBounds(200, 180, 90, 30);
        add(t11);
        t11.setBounds(200, 50, 90, 30);
        add(t12);
        t12.setBounds(200, 90, 90, 30);
        add(t13);
        t13.setBounds(200, 140, 90, 30);

        button1.setLabel("Exit");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(190, 240, 90, 30);

        button2.setLabel("Save");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(70, 240, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    public void closeCon(){
        try{
            con.close();
        }catch(Exception e){e.printStackTrace();}
    }
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        closeCon();
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        try{
            String s1=t11.getText();
            String s2=t12.getText();
            String s3=t13.getText();
            String s4=t14.getText();
            ps.setInt(1, Integer.parseInt(s1));
            ps.setString(2, s2);
            ps.setInt(3, Integer.parseInt(s3));
            ps.setString(4, s4);
            ps.executeUpdate();
            t11.setText("");
            t12.setText("");
            t13.setText("");
            t14.setText("");
            t11.requestFocus();
             
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

       closeCon();
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryForm().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.TextField t11;
    private java.awt.TextField t12;
    private java.awt.TextField t13;
    private java.awt.TextField t14;
    // End of variables declaration//GEN-END:variables
}
